### ISSUE TITLE
Allow dynamic registering of new data source 

### ISSUE THREAD

**Issue by ywang007** [blaze/blaze#1177]
1. Allowing different data source to be associated to different url path. 
For example, given a set of data:

```yaml
iris:
  source: sqlite:///../examples/data/iris.db
accounts:
  source: ../examples/data/accounts.json.gz
```
access each part separately via:
http://localhost:6363/iris,  
and
http://localhost:6363/accounts

 2. Further, allowing dynamic registering of new data source after the original construction of server, the server may start with empty data source, and grow as different data source become available. 

For example, adding a new piece

```yaml
cities:
  source: ../examples/data/cities.csv
```
to the server above on the run, and addressing the newly added via: http://localhost:6363/cities
