### ISSUE TITLE
Update blazer-server documentation and understand `data()` interface in order to do so

### ISSUE THREAD

**Issue by sandhujasmine** [blaze/blaze#1535]
Picking up the second heading from: #1507
Say we define a blaze server_conf.yaml file that points to the various example datasets:

server_conf.yaml:
```
iriscsv:
  source: {full_path_to_data}/iris.csv
irisdb:
  source: sqlite:///{full_path_to_data}/iris.db
accounts:
  source: {full_path_to_data}/accounts.json.gz 
  dshape: "var * {name: string, amount: float64}"
```

Full path to data can be obtained by:
```
In [1]: from blaze.utils import example
In [2]: full_path_to_data = example('iris.csv')
In [3]: full_path_to_data = example('iris.db')
In [4]: full_path_to_data = example('iris.accounts.json.gz')
```

Run `blaze-server server_conf.yaml` - server is running on: `http://127.0.0.1:6363/`. Now fire up ipython and try to load each dataset. I can query the 
```
# to access the underlying data, we can do the following
data('blaze://127.0.0.1:6363')['accounts']
data('blaze://127.0.0.1:6363')['iriscsv']
data('blaze://127.0.0.1:6363')['irisdb'].iris
```

Issues:
 * The iris data is not being accessed the same way for all three resources - this is confusing.
 * From #1357, it seems the `data()` and `symbol()` objects are similar `data()` is bound to a backend resource while `symbol()` is unbound. I don't fully understand the many ways in which `data()` can be used.
